from lauren import *

#WANT IT TO TAKE IN A GIVEN HID AND DIRECTORY NAME IN WHICH TO PUT THE FILES
#TRACE BACK USING ROCKSTAR HALO POSITIONS AND JUST DONT BOTHER WITH THE GROUPS
#THEN MAKE A PROJECTION CENTERED THE MMP FOR THAT TIMESTEP

#CHECK WHAT RADIUS I DID FOR MY FIRST MOVIE ATTEMPT BECAUSE I THINK THAT WAS A BIT TOO BIG. DEFINITELY TRY MAKING IT A BIT SMALLER.




